### ISSUE TITLE
Request: unwrap rspamd_logger.err and rspamd_logger.debug

### ISSUE THREAD

**Issue by cstrotm** [rseichter/rspamd-avast#2]
The functions unwrap rspamd_logger.err and rspamd_logger.debug are wrapped into _error and _debug. 

While that saves some typing (that can also be saved by using macros) it obfuscates the real line number where the error occurred (the line number in the log is always the wrapper function, not the real code where the error occurred)

This makes debugging harder than it should be

**Comment by rseichter** [comment]
I used functions like _debug() et al during initial development, to make it easier to debug when the code is not run within Rspamd. The code has now matured enough for me to get rid of these functions.
